# Generated by Django 3.2.12 on 2022-02-05 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_rm_unused_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pics_requested', models.IntegerField(default=0)),
                ('predicts', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tgbot.stats'),
        ),
    ]
