# Generated by Django 3.2.12 on 2022-02-05 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_auto_20220205_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stats',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tgbot.stats'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
