# Generated by Django 3.2.12 on 2022-02-05 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_auto_20220205_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stats',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tgbot.stats'),
        ),
    ]
